# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins: [jekyll-paginate]

# Permalinks
permalink:        /posts/:title

# Setup
title:            Nilaksh Das
description:      "Don't panic."
url:              http://nilakshdas.github.io
baseurl:          '/'
paginate:         5
paginate_path:    /posts/page-:num

author:
  name:           'Nilaksh Das'
  url:            https://twitter.com/nilakshdas
