# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems: [jekyll-paginate]

# Permalinks
permalink:        /posts/:title

# Setup
title:            Nilaksh Das
tagline:          'makes code'
description:      '"Be curious. Read widely. Try new things. What people call intelligence just boils down to curiosity." - Aaron Swartz'
url:              http://nilakshdas.github.io
baseurl:          '/'
paginate:         5
paginate_path:    /posts/page-:num

author:
  name:           'Nilaksh Das'
  url:            https://twitter.com/nilakshdas